train_path: prompt-injection/data/train-00000-of-00001.parquet
test_path: prompt-injection/data/test-00000-of-00001.parquet
format: parquet
model_name: cointegrated/rubert-tiny2
model_path:
output_dir: ./llm_defense_model
learning_rate: 2e-5
batch_size: 16
weight_decay: 0.01
epochs: 3
num_workers: 8
quantize: True